name: Release

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    uses: Mosher-Labs/.github/.github/workflows/release.yml@main
    with:
      enable_draft: ${{ github.event_name == 'pull_request' }}
      enable_release_notes: true
      enable_updates: true
    secrets: inherit
