name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: >
          xcodebuild test
          -project Renewed.xcodeproj
          -scheme Renewed
          -sdk iphonesimulator
          -destination "platform=iOS Simulator,name=iPhone 15"
